### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sahilappdeft**

### CODE REVIEW

**Comment by Synchro** [comment]
I see that this PR commits some credentials for both gmail and postgres; that's not good. We don't want anything like that in the commit history, even if you remove it later. Please can you rebase and force-push to remove those commits.

Generally speaking, I do not expect a configuration file like `local.py` to be in the repo at all, for exactly this reason. The usual thing would be to include a `local-dist.py` config template that contains empty/harmless placeholders for all the config settings, and a `.gitignore` entry to prevent adding the real config file to the repo.

**Comment by sahilappdeft** [comment]
> I see that this PR commits some credentials for both gmail and postgres; that's not good. We don't want anything like that in the commit history, even if you remove it later. Please can you rebase and force-push to remove those commits.
> 
> Generally speaking, I do not expect a configuration file like `local.py` to be in the repo at all, for exactly this reason. The usual thing would be to include a `local-dist.py` config template that contains empty/harmless placeholders for all the config settings, and a `.gitignore` entry to prevent adding the real config file to the repo.

I have rebased the commits and pushed the code. Please take a look at it.

**Comment by Synchro** [comment]
I'm not sure what you did here, but it's made a big mess. It looks like you rebased from the beginning of the project, not just the changes in this PR.

**Comment by Synchro** [comment]
One other thing – ignore my comment about not including `local.py`, that's fine, but what it should do is reference env vars set in `.env`, not to hard-code them. This is done in other places in `local.py` too.

**Comment by sahilappdeft** [comment]
> One other thing – ignore my comment about not including `local.py`, that's fine, but what it should do is reference env vars set in `.env`, not to hard-code them. This is done in other places in `local.py` too.

Okay, I apologize for this oversight. I’ll make sure to handle it correctly going forward.

**Comment by Synchro** [comment]
It might be best if you scrapped this PR and recreated it with just the changes needed for the delete function and the design tweaks – it's impossible to pick out your changes from what's in here.

**Comment by sahilappdeft** [comment]
> It might be best if you scrapped this PR and recreated it with just the changes needed for the delete function and the design tweaks – it's impossible to pick out your changes from what's in here.
i have recreated the PR look at it.

**Comment by sahilappdeft** [comment]
> It might be best if you scrapped this PR and recreated it with just the changes needed for the delete function and the design tweaks – it's impossible to pick out your changes from what's in here.

i recreated the PR  please look at it.

**Comment by Synchro** [comment]
I don't see a difference - the PR still contains the entire application in [this commit](https://github.com/agentGav/cl8/pull/2/commits/fa603c29b8c30478b3f36c9bba124b0ecd803d33).

**Comment by sahilappdeft** [comment]
drop

**Pull request closed without merging**
